spring:
  # thymeleaf 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  #jdbc ??
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.delivery.deliveryback


