spring:
  mvc:
    # thymeleaf 정적파일 경로 세팅
    static-path-pattern: /static/**
  thymeleaf:
    # thymeleaf html파일 경로 세팅
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
  # db 연결
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
# mybatis 설정
mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.delivery.delivery


