spring:
#jdbc ??
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: system
    password: system
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.delivery.deliveryback